services:
  db:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGPORT=${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data/

  app:
    build:
      context: ./good-habits-server
    command: >
      /bin/sh -c "
        alembic upgrade head &&
        poetry run uvicorn src.presentation.api.v1.main:app --host 0.0.0.0 --port 8000
      "
    env_file:
      - .env
    restart: always
    environment:
      PYTHONPATH: /app/src
      POSTGRES_URL: postgresql+asyncpg://postgres:123@db/goodhabits
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db

  bot:
    build:
      context: ./good-habits-server
    command: poetry run python -m src.presentation.bot.main
    env_file:
      - ./good-habits-server/.env
    restart: always
    depends_on:
      - db
    environment:
      PYTHONPATH: /app/src
      DB_HOST: db

  frontend:
    build:
      context: ./good-habits-client
    volumes:
      - frontend-dist:/app/dist
    command: /bin/sh -c "echo 'Frontend build completed' && cp -r /app/dist /frontend-dist/"
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend-dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend
      - app

volumes:
  pgdata:
  frontend-dist: